### ISSUE TITLE
(M2) Creacion de metodo 'listarUsuarios'

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/prjUfi-G1_C-S#25]
Este método imprime todos los usuarios de los ArrayList de 'Deportistas' y 'Padres'
Tiene que imprimir en un joptionPane toda la informacion de los usuarios.

Puede utilizar el codigo ya escrito y editarlo para que pueda imprimir todos los datos correspondientes! 
Puede generar un mini menu dentro del metodo para seleccionar que lista desea visualizar

**Comment by mjosevalverdep** [comment]
Tarea completada, descripción se encuentra en el historial
