### ISSUE TITLE
(M2P2) Metodo DesactivarDeporte

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/prjUfi-G1_C-S#34]
Deber recibir por parametros  nombre del deporte.
buscar si el deporte existe 
Si el deporte existe debera buscar si hay una rutina asignada al deporte.
si no lo esta se desactiva, si esta asignada muestra un mensaje de que no se puede desactivar
si no existe el deporte se muestra error

**Comment by Marcel1203** [comment]
Listo

**Comment by Marcel1203** [comment]
Listo
